[package]
name = "mqtt-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paho-mqtt = "0.11"
tokio = { version = "1", features = ["full"] }
env_logger = "0.7"
structopt = "0.3.26"
